# Generated by Django 5.2 on 2025-04-30 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firestation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fire_stations', to='fire.locations'),
        ),
        migrations.AlterField(
            model_name='firefighters',
            name='experience_level',
            field=models.CharField(choices=[('Probationary Firefighter', 'Probationary Firefighter'), ('Firefighter I', 'Firefighter I'), ('Firefighter II', 'Firefighter II'), ('Firefighter III', 'Firefighter III'), ('Driver', 'Driver'), ('Captain', 'Captain'), ('Battalion Chief', 'Battalion Chief')], max_length=150),
        ),
        migrations.AlterField(
            model_name='firefighters',
            name='station',
            field=models.ForeignKey(
                null=True,  # Allow NULL values
                blank=True, # Usually goes with null=True for consistency with forms/admin
                on_delete=django.db.models.deletion.SET_NULL, # If station is deleted, set firefighter's station to NULL
                related_name='firefighters',
                to='fire.firestation'
            ),
        ),
        migrations.AlterField(
            model_name='firetruck',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fire_trucks', to='fire.firestation'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='fire.locations'),
        ),
        migrations.AlterField(
            model_name='weatherconditions',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_conditions', to='fire.incident'),
        ),
    ]
