# Generated by Django 5.2 on 2025-04-30 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firestation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fire_stations', to='fire.locations'),
        ),
        migrations.AlterField(
            model_name='firefighters',
            name='experience_level',
            field=models.CharField(choices=[('Probationary Firefighter', 'Probationary Firefighter'), ('Firefighter I', 'Firefighter I'), ('Firefighter II', 'Firefighter II'), ('Firefighter III', 'Firefighter III'), ('Driver', 'Driver'), ('Captain', 'Captain'), ('Battalion Chief', 'Battalion Chief')], max_length=150),
        ),
        migrations.AlterField(
            model_name='firetruck',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fire_trucks', to='fire.firestation'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='fire.locations'),
        ),
        migrations.AlterField(
            model_name='weatherconditions',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_conditions', to='fire.incident'),
        ),
        # The following operations for Firefighters.station are commented out
        # because the field is a CharField in 0001_initial,
        # and the current models.py also defines it as a CharField.
        # The intermediate ForeignKey state in this migration (0002) and its reversal
        # in 0003 caused persistent errors.
        # # Step 1: Rename the existing 'station' CharField from 0001_initial.py
        # migrations.RenameField(
        #     model_name='firefighters',
        #     old_name='station',
        #     new_name='station_old_char',
        # ),
        # # Step 2: Add the new 'station' field as a ForeignKey.
        # # This will create a new 'station_id' column, populated with NULL for existing rows.
        # migrations.AddField(
        #     model_name='firefighters',
        #     name='station',
        #     field=models.ForeignKey(
        #         blank=True, # For forms/admin
        #         null=True,  # For the database
        #         on_delete=django.db.models.deletion.SET_NULL,
        #         related_name='firefighters',
        #         to='fire.firestation'
        #     ),
        #     preserve_default=False, # Ensures database NULL is used for existing rows
        # ),
        # # Step 3: Remove the old CharField (now renamed to station_old_char)
        # migrations.RemoveField(
        #     model_name='firefighters',
        #     name='station_old_char',
        # ),
    ]
