# Generated by Django 5.2 on 2025-05-24 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0002_firestation_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firestation',
            name='location',
        ),
        migrations.AlterField(
            model_name='firefighters',
            name='experience_level',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='firefighters',
            name='station',
            field=models.CharField(blank=True, choices=[('Probationary Firefighter', 'Probationary Firefighter'), ('Firefighter I', 'Firefighter I'), ('Firefighter II', 'Firefighter II'), ('Firefighter III', 'Firefighter III'), ('Driver', 'Driver'), ('Captain', 'Captain'), ('Battalion Chief', 'Battalion Chief')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='firetruck',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.firestation'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.locations'),
        ),
        migrations.AlterField(
            model_name='weatherconditions',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.incident'),
        ),
    ]
