# Generated by Django 5.2 on 2025-05-24 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0003_remove_firestation_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firefighters',
            name='rank',
            field=models.CharField(blank=True, choices=[('Probationary Firefighter', 'Probationary Firefighter'), ('Firefighter I', 'Firefighter I'), ('Firefighter II', 'Firefighter II'), ('Firefighter III', 'Firefighter III'), ('Driver', 'Driver'), ('Captain', 'Captain'), ('Battalion Chief', 'Battalion Chief')], max_length=150, null=True),
        ),
        # Step 1: Rename the existing 'station' CharField from 0001_initial.py
        migrations.RenameField(
            model_name='firefighters',
            old_name='station',
            new_name='station_old_charfield', # Renaming to avoid conflict
        ),
        # Step 2: Add the new 'station' field as a ForeignKey.
        # This will create a new 'station_id' column, populated with NULL for existing rows.
        migrations.AddField(
            model_name='firefighters',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firefighters', to='fire.firestation'),
            preserve_default=False, # Important for AddField to use database NULL for existing rows
        ),
        # Step 3: Remove the old CharField (now renamed)
        migrations.RemoveField(
            model_name='firefighters',
            name='station_old_charfield',
        ),
    ]
